const http = require("http");

let token = "demo-token";
let complaints = [
  {
    _id: "c1",
    name: "Rahul Kumar",
    email: "rahul@gmail.com",
    title: "Water Leakage Issue",
    description: "Water pipeline damaged near market area and water is flowing continuously.",
    category: "Water Supply",
    location: "Ghaziabad",
    status: "Pending",
    aiAnalysis: {
      urgency: "High",
      department: "Water Supply Department",
      summary: "Pipeline damage near market area causing continuous water leakage.",
      response: "Your complaint has been forwarded to the Water Supply Department."
    }
  }
];

const send = (res, statusCode, body) => {
  res.writeHead(statusCode, {
    "Access-Control-Allow-Headers": "Content-Type, Authorization",
    "Access-Control-Allow-Methods": "GET,POST,PUT,DELETE,OPTIONS",
    "Access-Control-Allow-Origin": "*",
    "Content-Type": "application/json"
  });
  res.end(JSON.stringify(body));
};

const readBody = (req) =>
  new Promise((resolve) => {
    let raw = "";
    req.on("data", (chunk) => {
      raw += chunk;
    });
    req.on("end", () => {
      resolve(raw ? JSON.parse(raw) : {});
    });
  });

http
  .createServer(async (req, res) => {
    if (req.method === "OPTIONS") {
      send(res, 200, {});
      return;
    }

    const body = await readBody(req);
    const url = new URL(req.url, "http://localhost");

    if ((url.pathname === "/api/register" || url.pathname === "/api/signup") && req.method === "POST") {
      send(res, 201, { _id: "u1", name: body.name, email: body.email, role: "Admin", token });
      return;
    }

    if (url.pathname === "/api/login" && req.method === "POST") {
      send(res, 200, { _id: "u1", name: "Kartik Upadhyay", email: body.email, role: "Admin", token });
      return;
    }

    if (url.pathname === "/api/complaints" && req.method === "GET") {
      send(res, 200, complaints);
      return;
    }

    if (url.pathname === "/api/complaints/search" && req.method === "GET") {
      const location = url.searchParams.get("location")?.toLowerCase();
      const category = url.searchParams.get("category")?.toLowerCase();
      send(
        res,
        200,
        complaints.filter((item) => {
          return (
            (!location || item.location.toLowerCase().includes(location)) &&
            (!category || item.category.toLowerCase().includes(category))
          );
        })
      );
      return;
    }

    if (url.pathname === "/api/complaints" && req.method === "POST") {
      const complaint = {
        _id: String(Date.now()),
        ...body,
        aiAnalysis: {}
      };
      complaints.unshift(complaint);
      send(res, 201, { message: "Complaint stored successfully.", complaint });
      return;
    }

    if (url.pathname.match(/^\/api\/complaints\/[^/]+$/) && req.method === "PUT") {
      const id = url.pathname.split("/").pop();
      complaints = complaints.map((item) => (item._id === id ? { ...item, status: body.status } : item));
      send(res, 200, { message: "Complaint status updated successfully.", complaint: complaints[0] });
      return;
    }

    if (url.pathname.match(/^\/api\/complaints\/[^/]+$/) && req.method === "DELETE") {
      const id = url.pathname.split("/").pop();
      complaints = complaints.filter((item) => item._id !== id);
      send(res, 200, { message: "Complaint removed successfully." });
      return;
    }

    if (url.pathname.match(/^\/api\/complaints\/[^/]+\/analyze$/) && req.method === "POST") {
      const id = url.pathname.split("/")[3];
      const complaint = complaints.find((item) => item._id === id) || complaints[0];
      complaint.aiAnalysis = {
        urgency: "High",
        department: "Water Supply Department",
        summary: "AI summary: the complaint reports civic water leakage requiring urgent action.",
        response: "Automatic response: Your complaint has been registered and forwarded."
      };
      send(res, 200, { message: "AI complaint analysis completed.", complaint });
      return;
    }

    if (url.pathname === "/api/ai/analyze" && req.method === "POST") {
      send(res, 200, {
        message: "AI analysis completed.",
        analysis: {
          urgency: "High",
          department: "Water Supply Department",
          summary: "Complaint summary generated by AI.",
          response: "Your complaint has been forwarded to the responsible department."
        }
      });
      return;
    }

    send(res, 404, { message: "Not found" });
  })
  .listen(5050, "127.0.0.1", () => {
    console.log("Mock API running at http://127.0.0.1:5050/api");
  });
